export function handleError(message: string, data: Record<string, any>) {
  console.error(message, data)
}
